<h1>Добавление товара</h1>
<hr/>

<form method="POST" enctype="multipart/form-data"><br>
    Name<br>
    <input type="text" name="name" value=""><br>
    Short Description<br>
    <textarea name="short_description"></textarea><br>
    Description<br>
    <textarea name="description"></textarea><br>
    Cost<br>
    <input type="number" name="cost" value=""><br>
    Quantity<br>
    <input type="number" name="count" value=""><br>
    Photo<br>
    <img src="" width="100px;"><br>
    <!--    <input type="file" name="photo"><br>-->
    <input type="text" name="photo" value=""><br>
    <select name="category">
      <?php foreach($categories as $item):?>
        <optgroup label="<?= $item['parent']->getName(); ?>">
            <?php if(!empty($item['children'])): ?>
                <?php foreach($item['children'] as $child): ?>
                    <option value="<?= $child->getId()?>">
                        <?= $child->getName();?>
                    </option>
                <?php endforeach; ?>
            <?php endif; ?>
        </optgroup>
      <?php endforeach;?>
    </select>
    <br><br>  <input type="submit" class="btn btn-success" value="Добавить">
</form>
<a href="/admin/goods" class="btn btn-default">Отменить</a>
