<h1>Goods CRUD</h1>

<p> module Admin <br/>
    controller Goods <br/>
    action add <br/>

<form method="POST" enctype="multipart/form-data"><br>
    Name<br>
    <input type="text" name="name" value=""><br>
    Short Description<br>
    <textarea name="short_description"></textarea><br>
    Description<br>
    <textarea name="description"></textarea><br>
    Cost<br>
    <input type="number" name="cost" value=""><br>
    Quantity<br>
    <input type="number" name="count" value=""><br>
    Photo<br>
    <img src="" width="100px;"><br>
    <!--    <input type="file" name="photo"><br>-->
    <input type="text" name="photo" value=""><br>
    <select name="category">
      <?php foreach($categories as $item):?>
        <optgroup label="<?= $item['parent']->getName(); ?>">
            <option value="<?= $item['parent']->getId()?>">
                -- <?= $item['parent']->getName();?> (Корень категории) --
            </option>
            <?php if(!empty($item['children'])): ?>
                <?php foreach($item['children'] as $child): ?>
                    <option value="<?= $child->getId()?>">
                        <?= $child->getName();?>
                    </option>
                <?php endforeach; ?>
            <?php endif; ?>
        </optgroup>
      <?php endforeach;?>
    </select>
  <br><br>  <input type="submit" value="Add">
</form>
<a href="/admin/goods"><button>Back</button></a>
