<div class="col-md-offset-3 col-md-6">
<?php
$flash = $this->flashMessenger();
$flash -> setMessageOpenFormat('<div%s>'
        . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
            . '&times;'
        . '</button>'
        . '<ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');
echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
</div>
<div class="col-md-12" align="center">
    <img src="<?php echo $this->basePath('img/galochka.jpg') ?>"  alt="ok"/>
</div>
<div class="col-md-12" align="center"><a href="<?= $this->url('guest', array('controller'=>'index', 'action' => 'index')) ?>" class="btn btn-info">На главную</a></div>
