<h1 class="text-center">Оформление заказа</h1>
<hr/>
<div class="col-md-offset-3 col-md-6">
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>'
                    . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
                    . '&times;'
                    . '</button>'
                    . '<ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>
<?php 
    $total_cost = 0;
    foreach ($cart as $item){
        $total_cost += $item['goods']->getCost() * $item['count'];
    }
?>
</div>
<div class="row">
    <div class="col-md-7">
        <form class="form-horizontal" id="form_order" method="POST" action="<?= $this->url('guest', array('controller' => 'order', 'action' => 'confirm')) ?>">
            <div class="form-group">
                <label for="name" class="col-md-offset-1 col-md-3 control-label">Имя</label>
                <div class="col-md-5">
                    <input type="text" name="customerName" placeholder="Имя" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="surname" class="col-md-offset-1 col-md-3 control-label">Фамилия</label>
                <div class="col-md-5">
                    <input type="text" name="customerSurname" placeholder="Фамилия" class="form-control" required/>
                </div>
            </div>

            <div class="form-group">
                <label for="city" class="col-md-offset-1 col-md-3 control-label">Город</label>
                <div class="col-md-5">
                    <select size="1"  name="city" class="form-control">   
                        <?php
                        $res = '';
                        for ($i = 0; $i < count($cities); $i++) {
                            $res.='<option value="' . $cities[$i]['id'] . '">' . $cities[$i]['city'] . '</option>';
                        }
                        echo $res;
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="adress" class="col-md-offset-1 col-md-3 control-label">Адресс</label>
                <div class="col-md-5">
                    <input type="text" name="adress" placeholder="Адресс" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="phone" class="col-md-offset-1 col-md-3 control-label">Телефон</label>
                <div class="col-md-5">
                    <input type="text" name="customerPhone" placeholder="Телефон" class="form-control" required/>
                    <span class="help-block" style="margin-bottom: 0;">Например: (050)555-55-55</span>
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-offset-1 col-md-3 control-label">Email</label>
                <div class="col-md-5">
                    <input type="email" name="customerEmail" placeholder="Email" class="form-control" required/>
                </div>
            </div>
            <div class="form-group">
                <label for="payment" class="col-md-offset-1 col-md-3 control-label">Тип оплаты</label>
                <div class="col-md-5">
                    <select size="1"  name="payment" class="form-control">   
                        <?php
                        $res = '';
                        for ($i = 0; $i < count($payment); $i++) {
                            $res.='<option value="' . $payment[$i]['id'] . '">' . $payment[$i]['paymentType'] . '</option>';
                        }
                        echo $res;
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="delivery" class="col-md-offset-1 col-md-3 control-label">Тип доставки</label>
                <div class="col-md-5">
                    <select size="1" name="delivery"  class="form-control">   
                        <?php
                        $res = '';
                        for ($i = 0; $i < count($delivery); $i++) {
                            $res.='<option value="' . $delivery[$i]['id'] . '">' . $delivery[$i]['deliveryType'] . '</option>';
                        }
                        echo $res;
                        ?>
                    </select>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-4" style="border: 2px #2a6496 solid;  border-radius: 15px ; margin-bottom: 15px;">
        <h3 class="text-center">Ваш заказ</h3>
        <?php
        $res = '<div align="left" style="margin-bottom: 30px;">';
        $res.='<table>';
        for($i=0; $i<count($cart); $i++){
            $res.='<tr style="border: 4px solid white;">';
            $res.='<td>' . $cart[$i]['goods']->getName() . '</td><td><div class="edit_goods_count" style="width: 45px; margin-left: 20px;" data-id="'.$cart[$i]['goods']->getId().'">' . $cart[$i]['count'] . ' шт.</div><td<br/>';
            $res.='</tr>';
        }
        $res.='</table></div>';
        echo $res;
        ?>
        <div class="row">
            <div class="col-sm-6 text-center">
                <h4>Сумма к оплате</h4>
            </div>
            <div class="col-sm-6 text-center">
                <h4><?= $total_cost; ?> грн.</h4>
            </div>
        </div>
    </div>
    <div class="row" style="margin-bottom: 15px;">
        <div class="col-sm-6 text-center">
            <input type="submit" value="Заказать" class="btn btn-success" form="form_order"/>
        </div>
        <div class="col-sm-6 text-center" style="margin-bottom: 5px;">
            <a class="btn btn-primary" href="<?= $this->url('guest', array('controller'=>'category')) ?>">Продолжить покупки</a>
        </div>
    </div>
</div>
