<div class="col-md-offset-3 col-md-6">
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>'
                    . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
                    . '&times;'
                    . '</button>'
                    . '<ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?>
</div>
<div class="col-md-8">
    <h1 class="text-center">Оформление заказа</h1>
    <hr/>
    <form class="form-horizontal" method="POST" action="<?= $this->url('guest', array('controller' => 'order', 'action' => 'confirm')) ?>">
        <div class="form-group">
            <label for="name" class="col-md-offset-1 col-md-3 control-label">Имя</label>
            <div class="col-md-5">
                <input type="text" name="customerName" placeholder="Имя" class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="surname" class="col-md-offset-1 col-md-3 control-label">Фамилия</label>
            <div class="col-md-5">
                <input type="text" name="customerSurname" placeholder="Фамилия" class="form-control" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="city" class="col-md-offset-1 col-md-3 control-label">Город</label>
            <div class="col-md-5">
                <select size="1"  name="city">   
                    <?php
                    $res = '';
                    for ($i = 0; $i < count($cities); $i++) {
                        $res.='<option value="' . $cities[$i]['id'] . '">' . $cities[$i]['city'] . '</option>';
                    }
                    echo $res;
                    ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="adress" class="col-md-offset-1 col-md-3 control-label">Адресс</label>
            <div class="col-md-5">
                <input type="text" name="adress" placeholder="Адресс" class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="phone" class="col-md-offset-1 col-md-3 control-label">Телефон</label>
            <div class="col-md-5">
                <input type="text" name="customerPhone" placeholder="Телефон" class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-md-offset-1 col-md-3 control-label">Email</label>
            <div class="col-md-5">
                <input type="email" name="customerEmail" placeholder="Email" class="form-control" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="delivery" class="col-md-offset-1 col-md-3 control-label">Тип доставки</label>
            <div class="col-md-5">
                <select size="1"  name="delivery">   
                    <?php
                    $res = '';
                    for ($i = 0; $i < count($payment); $i++) {
                        $res.='<option value="' . $payment[$i]['id'] . '">' . $payment[$i]['paymentType'] . '</option>';
                    }
                    echo $res;
                    ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="payment" class="col-md-offset-1 col-md-3 control-label">Тип оплаты</label>
            <div class="col-md-5">
                <select size="1"  name="payment">   
                    <?php
                    $res = '';
                    for ($i = 0; $i < count($delivery); $i++) {
                        $res.='<option value="' . $delivery[$i]['id'] . '">' . $delivery[$i]['deliveryType'] . '</option>';
                    }
                    echo $res;
                    ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-5">
                <input type="submit" value="Заказать" class="btn btn-primary"/>
            </div>
        </div>
    </form>
</div>
<div class="col-md-4" style="border: 2px #2a6496 solid;  border-radius: 15px ;">
    <h3 class="text-center">Ваш заказ</h3>
    <?php
    $res = '<div align="left" style="margin-bottom: 30px;">';
    $res.='<table>';
    for($i=0; $i<count($cart); $i++){
        $res.='<tr style="border: 4px solid white;">';
         $res.='<td>' . $cart[$i]['goods']->getName() . '</td><td><input class="edit_goods_count" type="number" value="' . $cart[$i]['count'] . '" min="1" style="width: 45px; margin-left: 7px;" data-id="'.$cart[$i]['goods']->getId().'"/><td<br/>';
        $res.='</tr>';
    }
    $res.='</table></div>';
    echo $res;
    ?>
</div>