<section id="content">
	<div class="main">
		<div class="indent-left">
			<div class="wrapper">
				<article class="col-1">
					<b>Наш Адрес</b>
					<div class="p1">
						<figure class="img-border">
							<div id="map_canvas">
								<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2645.884070066134!2d35.0382862158398!3d48.45875383671534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dbe2dfec037831%3A0xb8b03f96c277b337!2z0JrRgNCw0YHQvdCw0Y8g0YPQuy4sIDIx0JMsINCU0L3RltC_0YDQvtC_0LXRgtGA0L7QstGB0YzQuiwg0JTQvdGW0L_RgNC-0L_QtdGC0YDQvtCy0YHRjNC60LAg0L7QsdC70LDRgdGC0YwsIDQ5MDAw!5e0!3m2!1sru!2sua!4v1461935783244" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
							</div>
						</figure>
						<div class="clear"></div>
					</div>
					<ul class="contact">
						<li><i class="fa fa-map-marker" aria-hidden="true">&nbsp;&nbsp;&nbsp;</i>г. Днепропетровск, ул.Красная 21г.</li>
						<li><i class="fa fa-mobile" aria-hidden="true">&nbsp;&nbsp;&nbsp;</i>+(380)68 899 66 46</li>
						<li><i class="fa fa-envelope" aria-hidden="true">&nbsp;&nbsp;&nbsp;</i>petbox@gmail.com</li>
					</ul>
				</article>
				<article class="col-2">
					<b>Написать нам</b>
					<form id="contact-form">
						<fieldset>
							<label>
								<input type="text" value="Name" onBlur="if (this.value == '')
											this.value = 'Name'" onFocus="if (this.value == 'Name')
														this.value = ''" />
							</label>
							<label>
								<input type="text" value="Email" onBlur="if (this.value == '')
											this.value = 'Email'" onFocus="if (this.value == 'Email')
														this.value = ''" />
							</label>
							<label>
								<input type="text" value="Phone" onBlur="if (this.value == '')
											this.value = 'Phone'" onFocus="if (this.value == 'Phone')
														this.value = ''" />
							</label>
							<textarea onBlur="if (this.value == '')
										this.value = 'Message'" onFocus="if (this.value == 'Message')
													this.value = ''">Message</textarea>
							<div class="buttons-wrapper">
								<a class="btn btn-warning btn-sm" onClick="document.getElementById('contact-form').reset()">Clear</a>
								<a class="btn btn-primary btn-sm" onClick="document.getElementById('contact-form').submit()">Send</a>
							</div>
						</fieldset>
					</form>
				</article>
			</div>
		</div>
	</div>
</section>
<script type="text/javascript"> Cufon.now();</script>
