<h2>Список заказов</h2>
    
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>Номер</th>
            <th>Заказ</th>
            <th>Клиент</th>
            <th>Контактный телефон</th>
            <th>Статус</th>
            <th> </th>
        </tr>
        <?php
            foreach($orders as $order){
                echo "<tr>
                    <td>{$order[0]->getId()}</td>
                    <td>{$order[0]->getOrderList()}</td>
                    <td>{$order[0]->getCustomerName()}</td>
                    <td>{$order[0]->getCustomerPhone()}</td>
                    <td>{$order['orderStatus']}</td>";
               echo '<td><a href="'.$this->url('admin', array('controller'=>'order','action'=>'edit','id'=>$order[0]->getId())).'">Детали</a></td>';
                        
            }
        ?>
        <tbody>
</table>