<h2>Список заказов</h2>
<div class="actions">
    <form method="POST" class="form-horizontal" 
          action="<?= $this->url('admin', array('controller' => 'order', 'action' => 'search')) ?>">
        <input id="srch-term" type="text" name="search" placeholder="Поиск по статусу заказа.." size="50"/>&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-warning btn-sm">Найти</button>
    </form>
</div>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>Номер</th>
            <th>Заказ</th>
            <th>Клиент</th>
            <th>Контактный телефон</th>
            <th>Статус</th>
            <th> </th>
        </tr>
        <?php
        foreach ($orders as $order) {
            echo "<tr>
                    <td>{$order[0]->getId()}</td>
                    <td>{$order[0]->getOrderList()}</td>
                    <td>{$order[0]->getCustomerName()}</td>
                    <td>{$order[0]->getCustomerPhone()}</td>
                    <td>{$order['orderStatus']}</td>";
            echo '<td><a href="' . $this->url('admin', array('controller' => 'order', 'action' => 'edit', 'id' => $order[0]->getId())) . '">Детали</a></td>';
        }
        ?>
    <tbody>
</table>
