<h2>Список заказов</h2>
    
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>Номер</th>
            <th>Заказ</th>
            <th>Клиент</th>
            <th>Контактный телефон</th>
            <th> </th>
        </tr>
        <?php
            foreach($orders as $order){
                echo "<tr>
                    <td>{$order->getId()}</td>
                    <td>{$order->getOrder()}</td>
                    <td>{$order->getCustomerName()}</td>
                    <td>{$order->getCustomerPhone()}</td>";
               echo '<td><a href="'.$this->url('admin', array('action'=>'edit','id'=>$order->getId())).'">Детали</a></td>';
                        
            }
        ?>
        <tbody>
</table>