<h1>Категории</h1>

<?php
	$flash = $this->flashMessenger();
	$flash->setMessageOpenFormat('<div%s>
			<button type="button" class="close" data-dismiss="alert" aria-hidden"true">
				&times;
			</button>
			<ul><li>')
			->setMessageSeparatorString('</li><li>')
			->setMessageCloseString('</li></ul></div>');
	
	echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
	echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
	echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
	echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
	<tbody>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Parent</th>
			<th>Action</th>
		</tr>
		<?php $count = 1;  ?>
		<?php foreach($categories as $item): ?>
		<tr>
			<td><?php echo $count++; ?></td>
			<td><?php echo $item->getName() ?></td>
			<td><?php echo $item->getParent() ?></td>
			<td>
				<a href="<?php $this->url('admin/category', array('action' => 'edit', 'id' => $item->getId())) ?>">Edit</a>
				<a href="<?php $this->url('admin/category', array('action' => 'delete', 'id' => $item->getId())) ?>" onclick="if(confirm('Are u sure?')){document.location = this.href;} return false;">Delete</a>
			</td>
		</tr>	
		<?php endforeach; ?>
	</tbody>
</table>
<a href="<?php $this->url('admin/category', array('action' => 'add')) ?>" class="btn btn-info">Add</a>
<!--<a href="/admin/category/add/">Add</a>-->
<a href="<?php $this->url('admin/category', array('controller'=>'category', 'action' => 'add')) ?>" class="btn btn-info">Add</a>