<div class="c-cols-r-static" >
    <div class="col-md-12" align="center" >
        <h1>Категории</h1>
    </div>
    <div class="col-md-12" align="center" >
        <?php
        foreach ($categories as $item) {
            echo '<div class="col-md-3" ><div class="category_group"><div  class="category"><span> ';
            echo $item['parent']->getName();
            echo '</span></div>';
            for ($i = 0; $i < count($item['children']); $i++) {
                echo '<div class="subcategory">';
                $id=$item['children'][$i]->getId();
                echo '<li> <a href="' . $this->url('guest', array('controller' => 'goods', 'id' =>$id)).'">';
                echo($item['children'][$i]->getName());
                echo '</a></li></div>';
            }
            echo '</div></div>';
        }
        ?>
    </div>
</div>
