<div class="c-cols-r-static" >
    <div class="col-md-12" align="center" >
        <h1>Категории</h1>
    </div>
    <?php
    $category = array();
    $subcategory = array();
    foreach ($categories as $item) {
        $has_parent = $item->getParent();
        if (!$has_parent) {
            $res = '<a href="' . $this->url('guest', array('controller' => 'goods', 'id' => $item->getId())) . '">' . $item->getName() . '</a>';
            array_push($category, $res);
        } else {
            $res = '<a href="' . $this->url('guest', array('controller' => 'goods', 'id' => $item->getId())) . '">' . $item->getName() . '</a>';
            array_push($subcategory, $res);
        }
    }
    ?>
    <div class="col-md-12" align="center" >
        <h3>Выберите категорию</h3>
    </div>
    <div class="col-md-12" align="center" >
        <?php
        for ($i = 0; $i < count($category); $i++) {
            echo '<div class="col-md-3" ><div  class="category"><span> ';
            echo $category[$i];
            echo '</span></div></div>';
        }
        ?>
    </div>    
    <div class="col-md-12" align="center" >
        <h3>Подкатегории</h3>
    </div>
    <div class="col-md-12" align="center" >
        <?php
        for ($i = 0; $i < count($subcategory); $i++) {
            echo '<div class="col-md-3"><div  class="category"><span>';
            echo $subcategory[$i];
            echo '</span></div></div>';
        }
        ?>
    </div>
</div>
<!--
// старый код Саши, пока не удаляю-------------------------------------------------------------------------------------------------------
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>№</th>
            <th>Название</th>
            <th>Родительская</th>
        </tr>
        <?//php $count = 1; ?>
        <?//php foreach ($categories as $item): ?>
            <tr>
                <td><?//php echo $count++; ?></td>
                <td>
                    <a href="<?//= $this->url('guest', array('controller' => 'goods', 'id' => $item->getId())) ?>">
                        <?//php echo $item->getName() ?>
                    </a>
                </td>
                <td>
                    <?//php if ($item->getParent()):?> 
                        <a href="<?//= $this->url('guest', array('controller' => 'goods', 'id' => $item->getParent()->getId())) ?>">
                            <?//= $item->getParent()->getName(); ?>
                        </a>
                    <?//php endif; ?>
                </td>
            </tr>	
<?//php endforeach; ?>
    </tbody>
</table>-->