<div class="c-cols-r-static">
    <div class="col-md-12 id-good">
		<div class="col-md-6 id-img">
			<a class="fancybox" rel="group" href="<?php echo './public/img/goods/'.$goods->getPhoto() ?>"><img src="<?php echo './public/img/goods/'.$goods->getPhoto() ?>"/></a>
		</div>
		<div class="col-md-6 id-desc">
			<h2><?php echo $goods->getName() ?></h2>
			<p class="desc"><?php echo $goods->getDescription() ?></p></br>
			<label for="count">Количество:&nbsp;&nbsp;&nbsp;&nbsp;</label>
			<input type="number" name="goods_count" id="count" min="1" max="<?php echo $goods->getCount() ?>" step="1" value="1"/></br></br>
			<label for="exist">В наличии:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
			<span id="exist"><?php echo $goods->getCount() ?><span></br></br>
			<label for="price">Стоимость:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
			<span id="price"><?php echo $goods->getCost() ?> грн.<span></br></br>
			<a href="/guest/cart" class="btn">Купить</a>	
		</div>
	</div>
</div>
